// vue-project/vue/src/components/shared/Footer.vue
<template>
  <footer>

    <div class="side-by-side">
      chr.dc
    </div>

    <div class="side-by-side icons">
      <a href="https://twitter.com/chaordic">
        <img src="../../assets/images/icon-twitter.png" class="icon">
      </a>
      <a href="https://www.facebook.com/chaordic.com.br/">
        <img src="../../assets/images/icon-facebook.png" class="icon">
      </a>
    </div>

  </footer>
</template>

<script>
  export default {
    name: 'AppFooter'
  }
</script>

<style scoped>
  footer {
    height: 45px;
    vertical-align: middle;
    line-height: 45px;
  }
</style>

// project/view/src/app/footer/footer.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class FooterComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<footer>

  <div class="side-by-side">
    chr.dc
  </div>

  <div class="side-by-side icons">
    <a href="https://twitter.com/chaordic">
      <img src="../../assets/images/icon-twitter.png" class="icon">
    </a>
    <a href="https://www.facebook.com/chaordic.com.br/">
      <img src="../../assets/images/icon-facebook.png" class="icon">
    </a>
  </div>

</footer>
