// Project/project-linx/src/components/footer.jsx
import React from 'react';

import facebook from '../Assets/icon-facebook.png';
import twitter from '../Assets/icon-twitter.png';

function Footer(){
    return(
        <div className="center footer__geral">
            <div className="footer__chr">
                <p className="footer__chr__item">chr.dc</p>
            </div>
            <div className="footer__icons">
                <img src={twitter} alt="Ícone do Twitter" className="footer__icon__twitter"/>
                <img src={facebook} alt="Ícone do Facebook" className="footer__icon__facebook"/>
            </div>
        </div>
    )
}

export default Footer;

// vue-project/vue/src/components/shared/Footer.vue
<template>
  <footer>

    <div class="side-by-side">
      chr.dc
    </div>

    <div class="side-by-side icons">
      <a href="https://twitter.com/chaordic">
        <img src="../../assets/images/icon-twitter.png" class="icon">
      </a>
      <a href="https://www.facebook.com/chaordic.com.br/">
        <img src="../../assets/images/icon-facebook.png" class="icon">
      </a>
    </div>

  </footer>
</template>

<script>
  export default {
    name: 'AppFooter'
  }
</script>

<style scoped>
  footer {
    height: 45px;
    vertical-align: middle;
    line-height: 45px;
  }
</style>
